# Use Node base image + Python
FROM node:20

# Install yt-dlp dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg python3 python3-pip && \
    pip3 install yt-dlp

# Create app directory
WORKDIR /app

# Copy project files to container
COPY . .

# Install node dependencies
RUN npm install

# Start server
CMD ["npm", "start"]